version: 2
updates:
  - package-ecosystem: maven  # Update Java libraries
    directory: "/"
    schedule:
      interval: daily
    filters:
      - component: java  # Only update Java components
  - package-ecosystem: maven  # Ignore specific Maven dependencies
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin  # Example exclusion
  - package-ecosystem: "github-actions"  # Update GitHub Actions workflows
    directory: "/"
    schedule:
      interval: "daily"
