version: 2
updates:
    # Enable version updates for Gradle
    - package-ecosystem: "maven"
      directory: "/"
      # Check for updates once daily
      schedule:
          interval: "daily"
name: Build
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
